# Generated by Django 3.0.1 on 2019-12-25 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('First', (('+', 'Positive'), ('-', 'Negative'))), ('Second', (('+', 'Positive'), ('-', 'Negative'))), ('Third', (('+', 'Positive'), ('-', 'Negative'))), ('Fourth', (('+', 'Positive'), ('-', 'Negative')))], max_length=20)),
                ('allergies', models.CharField(max_length=120)),
                ('notes', models.CharField(max_length=120)),
                ('condition', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('calories', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.IntegerField()),
                ('ration', models.CharField(max_length=120)),
                ('duration', models.DurationField()),
                ('calories', models.IntegerField()),
                ('prohibitedFoods', models.CharField(max_length=120)),
                ('training', models.IntegerField()),
                ('water', models.FloatField()),
                ('time_of_sleep', models.IntegerField()),
                ('activity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=120)),
                ('lastName', models.CharField(max_length=120)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('height', models.IntegerField()),
                ('weight', models.FloatField()),
                ('daily_calories', models.IntegerField()),
                ('actual_calories', models.IntegerField()),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutrition.Program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('loss_weight', 'Loss weight'), ('balance', 'Balance'), ('mass_weight', 'Mass weight')], max_length=20)),
                ('products', models.ManyToManyField(to='nutrition.Product')),
            ],
        ),
    ]
