# Generated by Django 3.0.1 on 2019-12-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_auto_20191225_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='name',
            field=models.CharField(blank=True, default='Program', max_length=50, null=True),
        ),
    ]
